version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitIssuesMainProject
  gitServerName: test2
  gitUrl: https://github.com/PoojaAnandGit/TestGitIssuesMainProject
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.testgitissuesmain.integrations:e1
  packages:
  - name: TestGitIssuesMainProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.1002
- serviceName: project.testgitissuesmain.integrations:e2
  packages:
  - name: TestGitIssuesMainProject
    version: "1.0"
- serviceName: project.testgitissuesmain.integrations:newEdgelfow
  packages:
  - name: TestGitIssuesMainProject
    version: "1.0"
- serviceName: pub.date:calculateDateDifference
  packages:
  - name: WmPublic
    version: 11.0.0.0.996
